create table if not exists public.sync_users (
  id bigint generated by default as identity primary key,
  username_display text not null,
  username_norm text not null unique,
  password_salt text not null,
  password_hash text not null,
  password_iterations integer not null,
  role text not null default 'member' check (role in ('member', 'admin')),
  auth_version integer not null default 1,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.sync_sessions (
  token_hash text primary key,
  user_id bigint not null references public.sync_users(id) on delete cascade,
  auth_version integer not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists sync_sessions_user_idx on public.sync_sessions(user_id);
create index if not exists sync_sessions_expiry_idx on public.sync_sessions(expires_at);

create table if not exists public.sync_state_items (
  user_id bigint not null references public.sync_users(id) on delete cascade,
  kind text not null check (kind in ('job_status', 'offline_plan')),
  item_key text not null,
  value_json jsonb not null,
  client_updated_at timestamptz not null,
  last_seen_public_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, kind, item_key)
);
create index if not exists sync_state_retention_idx on public.sync_state_items(last_seen_public_at);

create table if not exists public.sync_reset_codes (
  code_hash text primary key,
  user_id bigint not null references public.sync_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

create table if not exists public.sync_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_registration_attempts (
  id bigint generated by default as identity primary key,
  network_hash text not null,
  attempted_at timestamptz not null default now()
);
create index if not exists sync_registration_rate_idx on public.sync_registration_attempts(network_hash, attempted_at);

create table if not exists public.sync_login_attempts (
  id bigint generated by default as identity primary key,
  attempt_key text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists sync_login_rate_idx on public.sync_login_attempts(attempt_key, attempted_at);

alter table public.sync_users enable row level security;
alter table public.sync_sessions enable row level security;
alter table public.sync_state_items enable row level security;
alter table public.sync_reset_codes enable row level security;
alter table public.sync_settings enable row level security;
alter table public.sync_registration_attempts enable row level security;
alter table public.sync_login_attempts enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
