import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const SESSION_DAYS=30, RETENTION_DAYS=90, ITERATIONS=210000, RESET_MINUTES=20;
const USER_RE=/^[A-Za-z0-9_]{3,24}$/; const enc=new TextEncoder();
class ApiError extends Error { status:number; constructor(status:number,message:string){super(message);this.status=status;} }
const iso=()=>new Date().toISOString();
const future=(ms:number)=>new Date(Date.now()+ms).toISOString();
function b64(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function token(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);return b64(b);}
async function sha(value:string){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(value))));}
async function digest(password:string,salt:string,iterations=ITERATIONS){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:enc.encode(salt),iterations},key,256)));}
function username(value:unknown){const display=String(value||"").trim();if(!USER_RE.test(display))throw new ApiError(400,"账号名须为3至24位字母、数字或下划线");return{display,norm:display.toLowerCase()};}
function password(value:unknown){const p=String(value||"");if(p.length<8||p.length>128)throw new ApiError(400,"密码须为8至128个字符");return p;}
async function passRecord(p:string){const salt=token(18);return{salt,hash:await digest(p,salt),iterations:ITERATIONS};}
async function passOk(p:string,u:any){const a=enc.encode(await digest(p,u.password_salt,u.password_iterations)),b=enc.encode(u.password_hash);if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0;}
async function secretRecord(s:string){const r=await passRecord(s);return`${r.iterations}:${r.salt}:${r.hash}`;}
async function secretOk(s:string,r:string|null){if(!r)return false;const[i,salt,hash]=r.split(":");return passOk(s,{password_salt:salt,password_hash:hash,password_iterations:Number(i)});}
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
function origin(req:Request){return(req.headers.get("Origin")||"").replace(/\/$/,"");}
function allowed(){return new Set((Deno.env.get("ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim().replace(/\/$/,"")).filter(Boolean));}
function headers(req:Request){const h:Record<string,string>={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"},o=origin(req);if(o&&allowed().has(o)){h["Access-Control-Allow-Origin"]=o;h.Vary="Origin";h["Access-Control-Allow-Headers"]="Authorization, Content-Type";h["Access-Control-Allow-Methods"]="GET, POST, PUT, DELETE, OPTIONS";}return h;}
function assertOrigin(req:Request){const o=origin(req);if(o&&!allowed().has(o))throw new ApiError(403,"此网页无权访问同步服务");}
async function body(req:Request){try{return await req.json();}catch{throw new ApiError(400,"请求内容格式错误");}}
function check(error:any){if(error)throw error;}
async function setting(key:string){const{data,error}=await db.from("sync_settings").select("value").eq("key",key).maybeSingle();check(error);return data?.value??null;}
async function setSetting(key:string,value:string){const{error}=await db.from("sync_settings").upsert({key,value,updated_at:iso()});check(error);}
async function bootstrap(){if(await setting("registration_open")===null)await setSetting("registration_open","1");if(await setting("invite_hash")===null){const v=Deno.env.get("INITIAL_INVITE_CODE");if(!v)throw new ApiError(503,"服务尚未完成邀请码初始化");await setSetting("invite_hash",await secretRecord(v));}}
async function ensureAdmin(){const au=Deno.env.get("ADMIN_USERNAME"),ap=Deno.env.get("ADMIN_PASSWORD");if(!au||!ap)throw new ApiError(503,"管理员账号尚未初始化");const n=username(au);const{data,error}=await db.from("sync_users").select("id").eq("username_norm",n.norm).maybeSingle();check(error);if(data)return;const r=await passRecord(password(ap));check((await db.from("sync_users").insert({username_display:n.display,username_norm:n.norm,password_salt:r.salt,password_hash:r.hash,password_iterations:r.iterations,role:"admin"})).error);}
async function issue(u:any){const t=token();check((await db.from("sync_sessions").insert({token_hash:await sha(t),user_id:u.id,auth_version:u.auth_version,expires_at:future(SESSION_DAYS*86400000)})).error);return t;}
async function auth(req:Request,role?:string){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))throw new ApiError(401,"请先登录");const th=await sha(h.slice(7));const{data:s,error}=await db.from("sync_sessions").select("user_id,auth_version,expires_at").eq("token_hash",th).gt("expires_at",iso()).maybeSingle();check(error);if(!s)throw new ApiError(401,"登录已失效");const{data:u,error:e}=await db.from("sync_users").select("*").eq("id",s.user_id).maybeSingle();check(e);if(!u||u.auth_version!==s.auth_version||(role&&u.role!==role))throw new ApiError(401,"登录已失效");return u;}
async function rateKey(req:Request,s=""){return sha(`${Deno.env.get("RATE_LIMIT_SECRET")||"job-board"}|${req.headers.get("x-forwarded-for")||"unknown"}|${s}`);}
async function register(req:Request){await bootstrap();if(await setting("registration_open")!=="1")throw new ApiError(403,"新账号注册目前已暂停");const key=await rateKey(req),since=future(-3600000);const{count,error}=await db.from("sync_registration_attempts").select("*",{count:"exact",head:true}).eq("network_hash",key).gt("attempted_at",since);check(error);if((count||0)>=5)throw new ApiError(429,"注册尝试过多，请稍后再试");check((await db.from("sync_registration_attempts").insert({network_hash:key})).error);const b=await body(req);if(b.consent!==true)throw new ApiError(400,"请先确认数据与隐私说明");const n=username(b.username),p=password(b.password);if(!await secretOk(String(b.inviteCode||""),await setting("invite_hash")))throw new ApiError(403,"班级邀请码无效");const r=await passRecord(p);const{data:u,error:e}=await db.from("sync_users").insert({username_display:n.display,username_norm:n.norm,password_salt:r.salt,password_hash:r.hash,password_iterations:r.iterations,last_login_at:iso()}).select().single();if(e?.code==="23505")throw new ApiError(409,"该账号名已被使用");check(e);return{token:await issue(u),username:n.display,expiresInDays:SESSION_DAYS};}
async function login(req:Request,admin=false){if(admin)await ensureAdmin();const b=await body(req);let n;try{n=username(b.username);}catch{throw new ApiError(401,"账号或密码错误");}const key=await rateKey(req,n.norm),since=future(-15*60000);const{count,error}=await db.from("sync_login_attempts").select("*",{count:"exact",head:true}).eq("attempt_key",key).eq("succeeded",false).gt("attempted_at",since);check(error);if((count||0)>=8)throw new ApiError(429,"登录尝试过多，请稍后再试");const{data:u,error:e}=await db.from("sync_users").select("*").eq("username_norm",n.norm).maybeSingle();check(e);const ok=!!u&&(!admin||u.role==="admin")&&await passOk(String(b.password||""),u);check((await db.from("sync_login_attempts").insert({attempt_key:key,succeeded:ok})).error);if(!ok)throw new ApiError(401,"账号或密码错误");check((await db.from("sync_users").update({last_login_at:iso()}).eq("id",u.id)).error);return{token:await issue(u),username:u.username_display,role:u.role,expiresInDays:SESSION_DAYS};}
async function getState(u:any){const{data,error}=await db.from("sync_state_items").select("kind,item_key,value_json,client_updated_at").eq("user_id",u.id).order("updated_at");check(error);return{items:(data||[]).map(x=>({kind:x.kind,key:x.item_key,value:x.value_json,updatedAt:x.client_updated_at}))};}
function validItem(x:any){return x&&["job_status","offline_plan"].includes(x.kind)&&typeof x.key==="string"&&x.key.length>0&&x.key.length<=1000&&!Number.isNaN(Date.parse(x.updatedAt||""))&&JSON.stringify(x.value).length<=4000;}
async function putState(req:Request,u:any){const b=await body(req),items=Array.isArray(b.items)?b.items:[],active=Array.isArray(b.activeKeys)?b.activeKeys:[];if(items.length>1000||active.length>5000||!items.every(validItem))throw new ApiError(400,"同步数据超出允许范围");const now=iso();for(const x of items){const{data:old,error}=await db.from("sync_state_items").select("client_updated_at").eq("user_id",u.id).eq("kind",x.kind).eq("item_key",x.key).maybeSingle();check(error);if(!old||Date.parse(x.updatedAt)>Date.parse(old.client_updated_at))check((await db.from("sync_state_items").upsert({user_id:u.id,kind:x.kind,item_key:x.key,value_json:x.value,client_updated_at:x.updatedAt,last_seen_public_at:now,updated_at:now})).error);}for(const x of active){if(x&&["job_status","offline_plan"].includes(x.kind)&&typeof x.key==="string")check((await db.from("sync_state_items").update({last_seen_public_at:now}).eq("user_id",u.id).eq("kind",x.kind).eq("item_key",x.key)).error);}return{ok:true,accepted:items.length};}
async function changePassword(req:Request,u:any){const b=await body(req);if(!await passOk(String(b.currentPassword||""),u))throw new ApiError(401,"当前密码错误");const r=await passRecord(password(b.newPassword)),v=u.auth_version+1;check((await db.from("sync_users").update({password_salt:r.salt,password_hash:r.hash,password_iterations:r.iterations,auth_version:v}).eq("id",u.id)).error);check((await db.from("sync_sessions").delete().eq("user_id",u.id)).error);return{token:await issue({...u,auth_version:v}),username:u.username_display,expiresInDays:SESSION_DAYS};}
async function deleteAccount(req:Request,u:any){if(u.role!=="member")throw new ApiError(403,"管理员账号不能从成员入口删除");const b=await body(req);if(!await passOk(String(b.password||""),u))throw new ApiError(401,"密码错误");check((await db.from("sync_users").delete().eq("id",u.id)).error);return{ok:true};}
async function stats(){const seven=future(-7*86400000),thirty=future(-30*86400000);const a=await db.from("sync_users").select("*",{count:"exact",head:true}).eq("role","member"),b=await db.from("sync_users").select("*",{count:"exact",head:true}).eq("role","member").gte("last_login_at",seven),c=await db.from("sync_users").select("*",{count:"exact",head:true}).eq("role","member").gte("last_login_at",thirty);check(a.error||b.error||c.error);return{registered:a.count||0,active7Days:b.count||0,active30Days:c.count||0,registrationOpen:await setting("registration_open")==="1"};}
async function adminSettings(req:Request){const b=await body(req);if(typeof b.registrationOpen==="boolean")await setSetting("registration_open",b.registrationOpen?"1":"0");if(b.newInviteCode!==undefined){const v=String(b.newInviteCode||"");if(v.length<8||v.length>128)throw new ApiError(400,"新邀请码须为8至128个字符");await setSetting("invite_hash",await secretRecord(v));}return{ok:true,registrationOpen:await setting("registration_open")==="1"};}
async function resetCode(req:Request){const b=await body(req),n=username(b.username);const{data:u,error}=await db.from("sync_users").select("id").eq("username_norm",n.norm).eq("role","member").maybeSingle();check(error);if(!u)throw new ApiError(404,"未找到该成员账号");const code=`${token(6).slice(0,8)}-${token(6).slice(0,8)}`;check((await db.from("sync_reset_codes").insert({code_hash:await sha(code),user_id:u.id,expires_at:future(RESET_MINUTES*60000)})).error);return{resetCode:code,expiresInMinutes:RESET_MINUTES};}
async function consumeReset(req:Request){const b=await body(req),n=username(b.username),h=await sha(String(b.resetCode||""));const{data:r,error}=await db.from("sync_reset_codes").select("user_id,expires_at,used_at").eq("code_hash",h).maybeSingle();check(error);const{data:u}=r?await db.from("sync_users").select("*").eq("id",r.user_id).eq("username_norm",n.norm).maybeSingle():{data:null};if(!r||!u||r.used_at||Date.parse(r.expires_at)<=Date.now())throw new ApiError(400,"重置码无效或已过期");const p=await passRecord(password(b.newPassword)),v=u.auth_version+1;check((await db.from("sync_reset_codes").update({used_at:iso()}).eq("code_hash",h)).error);check((await db.from("sync_users").update({password_salt:p.salt,password_hash:p.hash,password_iterations:p.iterations,auth_version:v}).eq("id",u.id)).error);check((await db.from("sync_sessions").delete().eq("user_id",u.id)).error);return{token:await issue({...u,auth_version:v}),username:u.username_display,expiresInDays:SESSION_DAYS};}
async function cleanup(){const now=iso();await db.from("sync_state_items").delete().lt("last_seen_public_at",future(-RETENTION_DAYS*86400000));await db.from("sync_sessions").delete().lt("expires_at",now);await db.from("sync_reset_codes").delete().or(`expires_at.lt.${now},used_at.not.is.null`);await db.from("sync_registration_attempts").delete().lt("attempted_at",future(-86400000));await db.from("sync_login_attempts").delete().lt("attempted_at",future(-86400000));return{ok:true};}
function adminPage(){return`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>看板管理后台</title><style>body{font-family:system-ui;background:#f1f5f9;color:#172033}.w{max-width:760px;margin:40px auto}.c{background:#fff;padding:24px;border-radius:12px;margin:16px}.hide{display:none}input,button{padding:10px;margin:4px}button{background:#2563eb;color:white;border:0;border-radius:7px}</style><main class=w><section class=c id=l><h1>管理员登录</h1><input id=u placeholder=管理员账号><input id=p type=password placeholder=密码><button onclick=login()>登录</button><p id=m></p></section><div id=panel class=hide><section class=c><h2>使用概览</h2><p>注册总人数：<b id=t></b>　近7天：<b id=d7></b>　近30天：<b id=d30></b></p><p id=rs></p></section><section class=c><button id=toggle onclick=toggleReg()>暂停注册</button><input id=invite type=password placeholder="新邀请码（至少8位）"><button onclick=rotate()>更换邀请码</button><p id=sm></p></section><section class=c><input id=member placeholder=成员准确账号名><button onclick=reset()>生成重置码</button><p id=rm></p></section></div></main><script>let token=sessionStorage.admin_token||'',s;const base=location.pathname.replace(/\/admin$/,'');async function api(path,o={}){const r=await fetch(base+'/api'+path,{...o,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(o.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}async function login(){try{let d=await api('/admin/login',{method:'POST',body:JSON.stringify({username:u.value,password:p.value})});token=d.token;sessionStorage.admin_token=token;await load()}catch(e){m.textContent=e.message}}async function load(){s=await api('/admin/stats');l.classList.add('hide');panel.classList.remove('hide');t.textContent=s.registered;d7.textContent=s.active7Days;d30.textContent=s.active30Days;rs.textContent=s.registrationOpen?'当前允许注册':'当前暂停注册';toggle.textContent=s.registrationOpen?'暂停注册':'恢复注册'}async function toggleReg(){await api('/admin/settings',{method:'PUT',body:JSON.stringify({registrationOpen:!s.registrationOpen})});await load()}async function rotate(){try{await api('/admin/settings',{method:'PUT',body:JSON.stringify({newInviteCode:invite.value})});invite.value='';sm.textContent='邀请码已更换'}catch(e){sm.textContent=e.message}}async function reset(){try{let d=await api('/admin/reset-code',{method:'POST',body:JSON.stringify({username:member.value})});rm.textContent='一次性重置码：'+d.resetCode+'（'+d.expiresInMinutes+'分钟内有效）'}catch(e){rm.textContent=e.message}}if(token)load()</script></html>`;}
async function route(req:Request){const url=new URL(req.url),marker="/job-board-sync",at=url.pathname.indexOf(marker);const path=at>=0?(url.pathname.slice(at+marker.length)||"/"):url.pathname;if(req.method==="OPTIONS"){assertOrigin(req);return new Response(null,{status:204,headers:headers(req)});}if(path==="/admin"&&req.method==="GET")return new Response(adminPage(),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}});assertOrigin(req);if((path==="/"||path==="/health")&&req.method==="GET")return{ok:true};if(path==="/api/register"&&req.method==="POST")return register(req);if(path==="/api/login"&&req.method==="POST")return login(req);if(path==="/api/admin/login"&&req.method==="POST")return login(req,true);if(path==="/api/reset/consume"&&req.method==="POST")return consumeReset(req);if(path==="/api/logout"&&req.method==="POST"){const h=(req.headers.get("Authorization")||"").slice(7);if(h)await db.from("sync_sessions").delete().eq("token_hash",await sha(h));return{ok:true};}const u=await auth(req);if(path==="/api/me"&&req.method==="GET")return{username:u.username_display,role:u.role};if(path==="/api/state"&&req.method==="GET")return getState(u);if(path==="/api/state"&&req.method==="PUT")return putState(req,u);if(path==="/api/change-password"&&req.method==="POST")return changePassword(req,u);if(path==="/api/account"&&req.method==="DELETE")return deleteAccount(req,u);if(path.startsWith("/api/admin/")){await auth(req,"admin");if(path==="/api/admin/stats"&&req.method==="GET")return stats();if(path==="/api/admin/settings"&&req.method==="PUT")return adminSettings(req);if(path==="/api/admin/reset-code"&&req.method==="POST")return resetCode(req);if(path==="/api/admin/cleanup"&&req.method==="POST")return cleanup();}throw new ApiError(404,"接口不存在");}
Deno.serve(async req=>{try{const result=await route(req);return result instanceof Response?result:new Response(JSON.stringify(result),{headers:headers(req)});}catch(e){const status=e instanceof ApiError?e.status:500;if(status===500)console.error(e);return new Response(JSON.stringify({error:status===500?"服务暂时不可用":e.message}),{status,headers:headers(req)});}});
